export const CATEGORIES = [
  "Groceries",
  "Dining",
  "Coffee",
  "Gas",
  "Transportation",
  "Travel",
  "Hotels",
  "Entertainment",
  "Streaming/Subscriptions",
  "Shopping - General",
  "Clothing",
  "Electronics",
  "Home Improvement",
  "Pharmacy/Health",
  "Medical",
  "Insurance",
  "Utilities",
  "Telecom/Internet",
  "Education",
  "Gifts/Donations",
  "Fees/Interest",
  "ATM/Cash Withdrawal",
  "Rent/Mortgage",
  "Services",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];
